
runtime: java
env: standard
runtime_config:
  jdk:openjdk8
  server:jetty9

service: 
  service_name: chat-service

handlers:
  -url: /.*
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
    
resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10
  volumes:
  - name: ram_disk_1
    volume_type: tmpfs
    size_gb: 0.1